image: alpine:latest

variables:
  DEPLOY_BRANCH: "pages"  # The branch name is fixed as 'pages'

stages:
  - deploy

pages:
  stage: deploy
  script:
    - apk update && apk add curl bash
    - echo "Downloading ZIP file..."
    - curl -L -o ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip "https://gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/-/archive/${DEPLOY_BRANCH}/${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip"
    - unzip ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip
    - rm ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip
    - mkdir public/
    - mv ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}/* public/
  artifacts:
    paths:
      - public
  only:
    - main